project_name: godnsagent
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - binary: godnsagent
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/globs you want to add to the archive.
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    files:
      - autocomplete/*
      - LICENSE*
      - CHANGELOG*
      - README*
      - godnsagent.defaults
      - godnsagent.service
